# Generated by Django 4.2.5 on 2023-09-18 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('phoneNo', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('reportTitle', models.CharField(max_length=100)),
                ('reportContent', models.TextField()),
                ('userID', models.IntegerField()),
                ('predictionID', models.IntegerField()),
                ('detailsID', models.IntegerField()),
                ('generatedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleID', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=20)),
                ('Desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userRoleID', models.AutoField(primary_key=True, serialize=False)),
                ('roleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.role')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('planID', models.AutoField(primary_key=True, serialize=False)),
                ('planDate', models.DateTimeField()),
                ('content', models.TextField()),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('predictionID', models.AutoField(primary_key=True, serialize=False)),
                ('predictionDate', models.DateTimeField()),
                ('result', models.IntegerField()),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('detailsID', models.AutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('cp', models.IntegerField()),
                ('trestbps', models.IntegerField()),
                ('chol', models.IntegerField()),
                ('fps', models.BooleanField()),
                ('restech', models.IntegerField()),
                ('thalach', models.IntegerField()),
                ('exang', models.BooleanField()),
                ('oldpeak', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slope', models.IntegerField()),
                ('ca', models.IntegerField()),
                ('thal', models.IntegerField()),
                ('target', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPatientRel',
            fields=[
                ('relationID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
        ),
    ]
