# Generated by Django 4.2.5 on 2023-09-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treats', models.ManyToManyField(blank=True, related_name='treated_by', to='user_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
        ),
    ]
