# Generated by Django 4.2.5 on 2023-09-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='doctor',
        ),
    ]
