# Generated by Django 4.2.5 on 2023-09-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_rename_user_profile_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='doctor',
            new_name='user',
        ),
    ]
