# Generated by Django 4.2.5 on 2023-09-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_doctor_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='doctor',
        ),
    ]
