# Generated by Django 4.2.5 on 2023-09-26 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0007_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpatientrel',
            name='patientID',
        ),
        migrations.RemoveField(
            model_name='doctorpatientrel',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='patientID',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='patientID',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='doctorID',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='patientID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='roleID',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='userID',
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DoctorPatientRel',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientDetails',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='TreatmentPlan',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
