# Generated by Django 4.2.5 on 2023-09-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_doctorpatientrel_patientid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='doctor',
            new_name='user',
        ),
    ]
