# Generated by Django 4.2.5 on 2023-09-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_patient_rename_phonenumber_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
