# Generated by Django 4.2.5 on 2023-10-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_profile_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('cp', models.IntegerField()),
                ('trestbps', models.IntegerField()),
                ('chol', models.IntegerField()),
                ('fps', models.BooleanField()),
                ('restech', models.IntegerField()),
                ('thalach', models.IntegerField()),
                ('exang', models.BooleanField()),
                ('oldpeak', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slope', models.IntegerField()),
                ('ca', models.IntegerField()),
                ('thal', models.IntegerField()),
                ('target', models.BooleanField()),
                ('dateModified', models.DateTimeField()),
                ('patientID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient')),
            ],
        ),
    ]
