# Generated by Django 4.2.5 on 2023-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_patientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='treats',
            field=models.ManyToManyField(blank=True, related_name='treated_by', to='user_app.patient'),
        ),
    ]
