# Generated by Django 4.2.5 on 2023-10-03 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_alter_profile_date_modified_alter_profile_treats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetails',
            old_name='patientID',
            new_name='patient',
        ),
    ]
