# Generated by Django 4.2.5 on 2023-10-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_rename_patientid_patientdetails_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
