# Generated by Django 4.2.5 on 2023-10-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_alter_patientdetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='ca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='chol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='cp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='dateModified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='exang',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='fps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='restech',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='slope',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='target',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='thal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='thalach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='trestbps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
