# Generated by Django 4.2.5 on 2023-10-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_doctorpatientrel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetails',
            old_name='fps',
            new_name='fbs',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='restech',
            new_name='restecg',
        ),
    ]
