# Generated by Django 4.2.5 on 2023-10-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_rename_fps_patientdetails_fbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
