# Generated by Django 4.2.5 on 2023-10-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_patientdetails_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='sex',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
