# Generated by Django 4.2.5 on 2023-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_patientdetails_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='sex',
            field=models.CharField(blank=True, choices=[('0', 'Male'), ('1', 'Female')], max_length=1, null=True),
        ),
    ]
