# Generated by Django 4.2.5 on 2023-10-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_alter_patientdetails_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='fbs',
            field=models.CharField(blank=True, choices=[('0', '  less than 120 mg/dl'), ('1', '  greater than 120 mg/dl')], max_length=1, null=True),
        ),
    ]
