# Generated by Django 4.2.5 on 2023-10-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_treatmentplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient'),
        ),
    ]
