# Generated by Django 4.2.5 on 2023-11-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0041_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
