# Generated by Django 4.2.5 on 2023-11-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0044_patientdetails_blood_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='dob',
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
