# Generated by Django 4.2.5 on 2023-11-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0047_predictionresult_delete_healthrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient'),
        ),
    ]
