# Generated by Django 4.2.5 on 2023-11-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0049_alter_predictionresult_options_predictionresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
