# Generated by Django 4.2.5 on 2023-11-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0050_alter_predictionresult_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartDiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('0', 'Male'), ('1', 'Female')], max_length=1, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('trestbps', models.IntegerField(blank=True, null=True)),
                ('chol', models.IntegerField(blank=True, null=True)),
                ('fbs', models.CharField(blank=True, choices=[('0', '  less than 120 mg/dl'), ('1', '  greater than 120 mg/dl')], max_length=1, null=True)),
                ('restecg', models.IntegerField(blank=True, null=True)),
                ('thalach', models.IntegerField(blank=True, null=True)),
                ('exang', models.CharField(blank=True, choices=[('0', 'Absence'), ('1', 'Presence')], max_length=1, null=True)),
                ('oldpeak', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('slope', models.IntegerField(blank=True, null=True)),
                ('ca', models.IntegerField(blank=True, null=True)),
                ('thal', models.IntegerField(blank=True, null=True)),
                ('prediction', models.CharField(max_length=10)),
                ('interpretation', models.TextField()),
                ('dateModified', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient')),
            ],
        ),
    ]
