# Generated by Django 4.2.5 on 2023-11-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0050_alter_predictionresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretary', 'Secretary'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('labTech', 'Lab Technician'), ('unassigned', 'Unassigned')], default='unassigned', max_length=12),
        ),
    ]
