# Generated by Django 4.2.5 on 2023-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0051_patientdetails_neg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='neg',
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='target',
            field=models.CharField(blank=True, choices=[('0', 'neg'), ('1', 'Pos')], max_length=1, null=True),
        ),
    ]
