# Generated by Django 4.2.5 on 2023-11-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0052_remove_patientdetails_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvitals',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient'),
        ),
    ]
