# Generated by Django 4.2.5 on 2023-11-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0052_alter_patientdetails_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='target',
            field=models.CharField(blank=True, choices=[('0', 'False'), ('1', 'True'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
    ]
