# Generated by Django 4.2.5 on 2023-11-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0053_alter_patientvitals_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvitals',
            name='blood_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
