# Generated by Django 4.2.5 on 2023-11-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0053_heartdiseaseprediction_delete_patientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient'),
        ),
    ]
