# Generated by Django 4.2.5 on 2023-11-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0054_alter_patientdetails_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient'),
        ),
    ]
