# Generated by Django 4.2.5 on 2023-11-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0055_alter_patientdetails_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='target',
            field=models.CharField(blank=True, choices=[('0', 'neg'), ('1', 'pos'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
    ]
