# Generated by Django 4.2.5 on 2023-11-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0055_alter_heartdiseaseprediction_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='exang',
            field=models.CharField(blank=True, choices=[(0, 'Absence'), (1, 'Presence')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='fbs',
            field=models.CharField(blank=True, choices=[(0, 'less than 120 mg/dl'), (1, 'greater than 120 mg/dl')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='heartdiseaseprediction',
            name='sex',
            field=models.CharField(blank=True, choices=[(0, 'Male'), (1, 'Female')], max_length=1, null=True),
        ),
    ]
