# Generated by Django 4.2.5 on 2023-11-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0055_profile_is_approved_labtest_doctorreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
