# Generated by Django 4.2.5 on 2023-11-26 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0056_alter_profile_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_vitals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.patientvitals')),
            ],
        ),
    ]
