# Generated by Django 4.2.5 on 2023-11-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0057_doctorcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcomments',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
