# Generated by Django 4.2.5 on 2023-11-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0058_alter_doctorcomments_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcomments',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.patient'),
        ),
    ]
