# Generated by Django 4.2.5 on 2023-11-26 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0059_alter_doctorcomments_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcomments',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.patient'),
        ),
        migrations.AlterField(
            model_name='doctorcomments',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorcomments',
            name='patient_vitals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_app.patientvitals'),
        ),
    ]
