# Generated by Django 4.2.5 on 2023-11-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0061_alter_labtest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(choices=[('typeA', 'Type A'), ('typeB', 'Type B'), ('typeC', 'Type C')], default='typeA', max_length=20),
        ),
    ]
