# Generated by Django 4.2.5 on 2023-11-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0062_alter_labtest_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(choices=[('typeA', 'CVD prediction'), ('typeB', 'Vitals'), ('typeC', 'X-ray')], default='typeA', max_length=20),
        ),
    ]
